apiVersion: autoscaling.infrared.reddit.com/v1alpha1
kind: RedditScaler
metadata:
  name: rscaler-scaler-cpu
spec:
  replicas:
    dynamic:
      enabled: true
      maxScaleCooldown: 300
      minScaleCooldown: 1
    max: 10
    min: 3
  scalers:
  - cpu:
      type: p95           # or "avg"
      thresholdPercent: 80
  target:
    deployment: ads-asset-management-cm-consumer