apiVersion: autoscaling.infrared.reddit.com/v1alpha1
kind: RedditScaler
metadata:
  name: rscaler-invalid-label
spec:
  replicas:
    dynamic:
      enabled: true
      maxScaleCooldown: 300
      minScaleCooldown: 1
    max: 5
    min: 2
  scalers:
  - adaptive: {}
  target:
    deployment: ads-asset-management