apiVersion: autoscaling.infrared.reddit.com/v1alpha1
kind: RedditScaler
metadata:
  name: rscaler-missing-cpu
spec:
  replicas:
    dynamic:
      enabled: false
      maxScaleCooldown: 300
      minScaleCooldown: 1
    max: 200
    min: 40
  scalers:
  - adaptive: {}
  - cpu:
      thresholdPercent: 69
      type: avg
  target:
    deployment: post-thrift-mailroom