apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-thrift-mailroom
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-thrift-mailroom
  template:
    metadata:
      labels:
        app: post-thrift-mailroom
        infrared.reddit.com/deployment: post-thrift-mailroom  # REQUIRED
    spec:
      containers:
        - name: consumer
          image: nginx:stable
          ports:
            - containerPort: 80