apiVersion: autoscaling.infrared.reddit.com/v1alpha1
kind: RedditScaler
metadata:
  name: rscaler-missing-cpu
spec:
  replicas:
    dynamic:
      enabled: true
      maxScaleCooldown: 300
      minScaleCooldown: 1
    max: 100
    min: 3
  scalers:
  - adaptive: {}
  - CPU:
    thresholdPercent: 69
    type: avg
  target:
    deployment: post-thrift-mailroom