apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authorizer
  template:
    metadata:
      labels:
        app: authorizer
        infrared.reddit.com/deployment: authorizer  # REQUIRED
    spec:
      containers:
        - name: consumer
          image: nginx:stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"