apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-asset-management
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ads-asset-management
  template:
    metadata:
      labels:
        app: ads-asset-management
    spec:
      containers:
        - name: consumer
          image: nginx:stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"